<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.doctrine.orm.default.subresource_data_provider' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/Bridge/Doctrine/Orm/Util/IdentifierManagerTrait.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/Bridge/Doctrine/Orm/SubresourceDataProvider.php';

return $this->privates['api_platform.doctrine.orm.default.subresource_data_provider'] = new \ApiPlatform\Core\Bridge\Doctrine\Orm\SubresourceDataProvider(($this->services['doctrine'] ?? $this->getDoctrineService()), ($this->privates['api_platform.metadata.property.name_collection_factory.cached'] ?? $this->getApiPlatform_Metadata_Property_NameCollectionFactory_CachedService()), ($this->privates['api_platform.metadata.property.metadata_factory.cached'] ?? $this->getApiPlatform_Metadata_Property_MetadataFactory_CachedService()), new RewindableGenerator(function () {
    yield 0 => ($this->privates['api_platform.doctrine.orm.query_extension.filter'] ?? $this->load('getApiPlatform_Doctrine_Orm_QueryExtension_FilterService.php'));
    yield 1 => ($this->privates['api_platform.doctrine.orm.query_extension.order'] ?? $this->load('getApiPlatform_Doctrine_Orm_QueryExtension_OrderService.php'));
    yield 2 => ($this->privates['api_platform.doctrine.orm.query_extension.pagination'] ?? $this->load('getApiPlatform_Doctrine_Orm_QueryExtension_PaginationService.php'));
}, 3), new RewindableGenerator(function () {
    return new \EmptyIterator();
}, 0));
