<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJSx3SSw\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJSx3SSw/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJSx3SSw.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJSx3SSw\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJSx3SSw\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'JSx3SSw',
    'container.build_id' => 'ef4bb22a',
    'container.build_time' => 1533397249,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJSx3SSw');
